### PR TITLE
Adds 'reset' rule to docs

### LINKED ISSUE #11: Add docs for `reset`
Seems i forgot about that.

### PR DESCRIPTION
**Pull request by zcei**
Fixes #11

### CODE REVIEW

**Comment by wooorm** [comment]
Thanks for the work, I have to disappoint however, as the `doc/rules` file is generated by `script/build-rule-documentation.js` (thus, it’ll be overwritten).

could you add the same to that file, and try executing `npm run build-md`?

**Comment by wooorm** [comment]
Thanks!

**Comment by zcei** [comment]
Ohh, now I was currently working on an abstraction, to allow "meta" rules, to not have every such rules hardcoded.

Still wanted for further "file-less" rules? Nearly done.

**Comment by wooorm** [comment]
Oh sorry, didn't know. Well it won't hurt to look at them :)

Could you add those to a new branch? I’ll gladly check ’em out!

**Comment by zcei** [comment]
I literally opened the issue to tell you in the second I received the mail, that it has been merged.

No worries, will apply everything to a new branch :+1:

**Pull request merged**
